In [1]:
import cv2
from keras.models import load_model
import numpy as np
model = load_model('keras_model.h5')
cap = cv2.VideoCapture(0)
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

while True: 
    ret, frame = cap.read()
    resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
    image_np = np.array(resized_frame)
    normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
    data[0] = normalized_image
    prediction = model.predict(data)
    cv2.imshow('frame', frame)
    # Press q to close the window
    print(prediction)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
            
# After the loop release the cap object
cap.release()
# Destroy all the windows
cv2.destroyAllWindows()

2022-03-07 21:24:36.566699: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-03-07 21:24:36.567733: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


Metal device set to: Apple M1

systemMemory: 8.00 GB
maxCacheSize: 2.67 GB



2022-03-07 21:24:39.769588: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2022-03-07 21:24:40.002756: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


[[3.4202153e-06 6.7495006e-01 3.2492763e-01 1.1895304e-04]]
[[5.3371231e-08 9.9947029e-01 8.9800647e-05 4.3991674e-04]]
[[8.0259337e-09 9.9960846e-01 5.8890178e-05 3.3273944e-04]]
[[5.6085142e-08 9.9956030e-01 2.1299790e-04 2.2665993e-04]]
[[8.8784176e-08 9.9940467e-01 4.1607567e-04 1.7919521e-04]]
[[9.7126545e-08 9.9965632e-01 2.7689803e-04 6.6788882e-05]]
[[2.2250622e-06 9.9875712e-01 6.4196764e-04 5.9865939e-04]]
[[1.7839819e-05 9.9700505e-01 7.5572316e-04 2.2213070e-03]]
[[2.7141373e-06 9.9746138e-01 4.0772095e-04 2.1281494e-03]]
[[7.9288009e-07 9.9871957e-01 2.4637821e-04 1.0332924e-03]]
[[2.0947141e-06 9.9175644e-01 4.1066358e-04 7.8308759e-03]]
[[2.5054620e-04 8.5284567e-01 2.9850095e-03 1.4391880e-01]]
[[7.0352969e-04 7.7444661e-01 6.3437663e-02 1.6141227e-01]]
[[1.3808084e-04 1.6899815e-02 4.3099824e-02 9.3986225e-01]]
[[2.1911970e-05 6.0982425e-03 5.9318799e-03 9.8794800e-01]]
[[1.7306819e-07 3.6723760e-01 7.0478400e-04 6.3205743e-01]]
[[4.9849106e-05 6.7646459e-02 1.3056745e