In [1]:
import cv2
from keras.models import load_model
import numpy as np
import random
model = load_model('keras_model.h5')
cap = cv2.VideoCapture(0)
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

while True: 
    ret, frame = cap.read()
    resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
    image_np = np.array(resized_frame)
    normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
    data[0] = normalized_image
    prediction = model.predict(data)
    cv2.imshow('frame', frame)
    # Press q to close the window

    if(prediction[0][3]) > 0.8:
        user_choice = ('None')
    elif(prediction[0][1]) > 0.8:
        user_choice = ('Paper')
    elif(prediction[0][2]) > 0.8:
        user_choice = ('Scissors')
    else:
        user_choice = ('Rock')
    print(f'You chose {user_choice}')

    computer_choice = random.choice(['Rock','Paper','Scissors'])
    print(f'Computer chose {computer_choice}')

    if user_choice == 'Rock' and computer_choice == 'Paper':
        print('Computer Won!')
    elif user_choice == 'Rock' and computer_choice == 'Scissors':
        print('You Won!')
    elif user_choice == 'None':
        print('You Chose Nothing, You Lost!')
    elif user_choice == 'Paper' and computer_choice == 'Rock':
        print('You Won!')
    elif user_choice == 'Paper' and computer_choice == 'Scissors':
        print('You Lost!')
    elif user_choice == 'Scissors' and computer_choice == 'Rock':
        print('You Lost!')
    elif user_choice == 'Scissors!' and computer_choice == 'Paper':
        print('You Won!')
    else:
        print('Draw')


    computer_choice = random.choice(['Rock','Paper','Scissors'])
    print(f'Computer chose {computer_choice}')

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
# After the loop release the cap object
cap.release()
# Destroy all the windows
cv2.destroyAllWindows()

2022-03-09 10:55:58.266344: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-03-09 10:55:58.266437: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


Metal device set to: Apple M1

systemMemory: 8.00 GB
maxCacheSize: 2.67 GB



2022-03-09 10:56:00.566163: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2022-03-09 10:56:00.772856: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


[2.7172789e-06 7.8881747e-01 2.1112125e-01 5.8561389e-05]
[2.1045899e-08 9.9999928e-01 7.1293664e-07 5.7049494e-08]
[7.6290512e-08 9.9999070e-01 7.9907095e-06 1.1883021e-06]
[9.6112105e-09 9.9999905e-01 8.7908137e-07 6.3760446e-08]
[2.8632421e-08 9.9999905e-01 9.5322207e-07 4.1245485e-08]
[1.5979815e-08 9.9999857e-01 1.4541774e-06 5.1366666e-08]
[1.21926425e-08 9.99999762e-01 2.41096615e-07 3.11587840e-08]
[2.2967720e-08 9.9999964e-01 3.2410142e-07 2.6797956e-08]
[2.5911771e-08 9.9999964e-01 3.6927383e-07 4.6340343e-08]
[3.4896939e-08 9.9999964e-01 3.5545008e-07 2.6839688e-08]
[6.2063833e-08 9.9999964e-01 3.5353980e-07 3.7148521e-08]
[1.6033734e-08 9.9999976e-01 2.0097649e-07 2.8910458e-08]
[2.9008008e-08 9.9999964e-01 3.0271883e-07 4.9249198e-08]
[5.8848538e-08 9.9999952e-01 4.7172659e-07 4.2594397e-08]
[1.29308635e-08 9.99999404e-01 5.66541416e-07 1.47681787e-08]
[8.9678966e-09 9.9999928e-01 6.8852796e-07 1.4532118e-08]
[2.0692278e-08 9.9999917e-01 7.6680874e-07 2.1833397e-08]
[9.606